jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: <the password you assigned to POSTGRES_PASSWORD>
      port: 5432
      dbname: dbt_training
      schema: dbt_test
      threads: 4
